### ISSUE TITLE
Unable to install in VS 2017 RC

### ISSUE THREAD

**Issue by suttonandy** [madskristensen/WebAccessibilityChecker#13]
### Installed product versions
- Visual Studio 2017 RC
- Package Security Alerts 1.0.17

### Current behavior
The extension fails to install.  The following is written to the log file.  I have tried many times but it results in the same error.

23/01/2017 20:56:29 - The extension with ID '1fd37423-142f-4267-8221-93163d573b90' is not installed to Microsoft Visual Studio Enterprise 2017 RC.
23/01/2017 20:56:43 - The following target products have been selected...
23/01/2017 20:56:43 - 	Microsoft Visual Studio Enterprise 2017 RC
23/01/2017 20:56:43 - 
23/01/2017 20:56:44 - Beginning to install extension to Microsoft Visual Studio Enterprise 2017 RC...
23/01/2017 20:56:44 - Install Error : System.IO.FileNotFoundException: Unable to find the specified file.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetCurrentSetupInstance()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by madskristensen** [comment]
It now works in VS2017
